### ISSUE TITLE
Enhancement: use tabs for different samples in IGVjs

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#107]
Currently we're using a rudimentary `tree` HTML page as an index to the different IGVjs visualizations. We then embedded a Javascript back button to return to the index page. However, this functions exactly like the browser's back button, thus, when moving around with the in-site hyperlinks it simply returns to that anchor instead of the index page. 

A solution would be to make a tabular IGVjs HTML similar to https://igv.org/web/release/2.3.5/examples/tabs.html.

It's a minor issue/inconvenience, so it has low priority. Will probably be fixed early 2020.

**Comment by florianzwagemaker** [comment]
Fixed in #108
