### ISSUE TITLE
Adapter trimming SISPA K-primer 

### ISSUE THREAD

**Issue by jeroencremer** [DennisSchmitz/Jovian_archive#11]
Ad to parameters option to use trimming for SISPA protocol.

>K-primer
GACCATCTAGCGACCTCCAC
>Reverse-complement_K-primer
GTGGAGGTCGCTAGATGGTC

**Comment by DennisSchmitz** [comment]
Added it in  9916f7a . Can you test it please?

**Comment by florianzwagemaker** [comment]
As said, SIPSA-K primers should work in release **0.9.1** of jovian.
Closing this issue now under the assumption that this is functioning as intended but this still requires extra verification.

@jeroencremer @thierryjanssens Could you please verify if this release (0.9.1) works as intended for SISPA-K primer trimming?

In case it doesn't work as intended then please re-open this issue
