### ISSUE TITLE
Validation and incorporation of new BLAST databases

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#115]
Originally reported by Sam Nooij:

NCBI is working on new BLAST databases, see https://ftp.ncbi.nlm.nih.gov/blast/db/v5/blastdbv5.pdf. Besides new functionality they've managed to downsize the database significantly. Might be useful to look into/validate.

It requires `blast` version >`2.80`, and the `Jovian` uses version `2.7.1`. Would be a good upgrade for a future version, pending benchmarking results.

See ftp://ftp.ncbi.nlm.nih.gov/blast/db/v5/, apparently NT and NR go from 85 and 141 `tar.gz` files to 21 and 30, respectively. Unsure of the actual filesize also shows such a decrease.

**Comment by florianzwagemaker** [comment]
New BLAST compatibility is added in https://github.com/DennisSchmitz/Jovian/pull/118

Succesfully validated against a minor dataset for testing. Requires a larger validation set before next release of (sub)version

**Comment by florianzwagemaker** [comment]
No abnormalities seen with larger datasets. Going to just assume this is solved.
