### ISSUE TITLE
Improvement/clarification: make a cluster-queue flag in the wrapper with priority

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#126]
Currently, the contents of `profile/config.yaml` are overwritten with the master-settings in `~/.jovian_installchoices_compmode`. Even if you manually overwrite the queue settings in the former file, they are overwritten by the master-settings since this has priority. This is confusing. The wrapper needs a flag that can assign a queue that overwrites any and all other specifications.

**Comment by florianzwagemaker** [comment]
Added in https://github.com/DennisSchmitz/Jovian/commit/ca934db91547d9cd8e5fc91a28491f54fa562810

Will be merged into master once possible
