### ISSUE TITLE
Known issue: Installation of conda environments is very slow

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#14]
It can take over an hour to install the conda environments required for Jovian to function. Sadly, this is not something we can fix. See [here](https://github.com/conda/conda/issues/7239).

Furthermore, it looks like generating conda environments cannot be done in parallel, see [here](https://bitbucket.org/snakemake/snakemake/issues/542/parallelize-conda-environment-creation).

**Comment by dnieuw** [comment]
Depends on your system, took me 20 mins or so

**Comment by DennisSchmitz** [comment]
Is that only for the Jovian_master environment or for the entire pipeline? If the latter, that would be interesting for us to sort out.

**Comment by dnieuw** [comment]
For the master and the helper environment, the main issue is downloading the databases. That takes hours on our 20MB/s network... So I wouldn't say that the pipeline installation takes very long, relatively speaking.
BTW, just remembered that I have anaconda, not miniconda, installed, that probably increases the speed of setting up the environments.

**Comment by DennisSchmitz** [comment]
Yeah, but after the master and helper environment you need to install 8 more environments. So that also takes some time. About the databases, updater scripts will be added in later version of the bash wrapper.

**Comment by dnieuw** [comment]
I see, installing the additional environments takes about an extra hour for me indeed.

**Comment by DennisSchmitz** [comment]
Blog post by Anaconda on Conda's performance, worth reading: https://www.anaconda.com/understanding-and-improving-condas-performance/

**Comment by DennisSchmitz** [comment]
For anyone reading this, switching from a [NFS file system](https://en.wikipedia.org/wiki/Network_File_System) to a [Lustre file](https://en.wikipedia.org/wiki/Lustre_(file_system)) system helps a lot.

**Comment by DennisSchmitz** [comment]
I'm unpinning this issue since using the `Lustre` filesystem fixes this completely.
