### ISSUE TITLE
SPAdes error correction takes very long for some samples

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#144]
I have been running a number bacterial metagenomes through Jovian and for some of the samples the _de novo_ assembly step takes much longer than what seems normal. When looking through the log files, it seems SPAdes's error correction step takes several days (5 or more), whereas the assembly itself only takes a few hours. With other samples of similar size this is no issue and error correction finishes in < 12 hours.

This seems to be a known issue with SPAdes (see https://github.com/ablab/spades/issues/152). As a workaround it is suggested to skip the error correction step with the `--only-assembler` parameter.

This error occurs with SPAdes version 3.11.0-py36_0 (the current standard in Jovian). I can manually update to a newer version (3.14.0 is available via conda now) and see if that helps. Otherwise, I can try the suggested workaround of skipping error correction and hope that strictly trimmed reads (Jovian strict setting: `SLIDINGWINDOW:5:30` with trimmomatic) yield decent assemblies.

**Comment by aschuerch** [comment]
I would really recommend to use the --only-assembler option and to skip the error correction option. I am not sure how it works for metagenomes, but for whole genomes, the error correction option introduces errors sometimes, especially if you are dealing with a mixture of strains (which might well be the case in a metagenome).

**Comment by samnooij** [comment]
Thanks for the information @aschuerch ! I will give `--only-assembler` a try on these metagenomes then.  :)

**Comment by DennisSchmitz** [comment]
Thanks to you both for the information! :)

@amberhendriks also mentioned on slack that updating to the latest version doesn't fix this issue. Something to assess for the next release.

**Comment by florianzwagemaker** [comment]
The `--only-assembler` option was included in https://github.com/DennisSchmitz/Jovian/commit/a879dfaa85e303434cce6799fa8a4a560dfcce8d

Haven't seen any problems with assembly since, so we'll close this issue for now
