### ISSUE TITLE
Somehow pygraphviz 1.3.1 won't download/install automatically

### ISSUE THREAD

**Issue by dnieuw** [DennisSchmitz/Jovian_archive#15]
While generating the required master environment bioconda's pygraphviz 1.3.1 keeps on failing to download/install. I manually tried installing via `conda install -c bioconda pygraphviz`, which installs no problem. After that, rerunning the env create runs just fine.

So something fishy is going on, if you do not totally rely on bioconda's pygraphviz 1.3.1 I'd recommend using a different version/conda repo.

Cheers,

David

P.S. Might also just be our system, since it's such a weird bug.

**Comment by DennisSchmitz** [comment]
That's weird indeed, we had/have no problems. Which version are you using? Otherwise I`ll just set that version as a requirement.

**Comment by dnieuw** [comment]
I did not have pygraphviz, thats why I installed it, currently I have 1.3.1 available through the "manual" install. I would have to test a clean install with a different version of pygraphviz to figure out which one works out of the box.

**Comment by DennisSchmitz** [comment]
Doing a cleanup of the issues. Closing this for now.
