### ISSUE TITLE
Rule Krona_chart_and_LCA does not work

### ISSUE THREAD

**Issue by dnieuw** [DennisSchmitz/Jovian_archive#17]
`rule Krona_chart_and_LCA:`

This rule doesn't work for me, Krona can't find my accessions DB, which I have installed and updated via updateaccessions.sh using the Jovian_helper env.

While running snakemake from the Jovian_master env, snakemake uses my local krona installation, which does not have the accessions DB. 

I'm not entirely sure what kind of fix you have in this rule (creating simlinks?), but for me it does not work. Also, looks a bit hacky :-1: 

Is this a permanent thing or a quick-fix?

Cheers,

David

**Comment by DennisSchmitz** [comment]
Sat down with David and checked it... Issue resolved its-self when the .conda/[hash]/opt/krona/taxonomy folder was removed. Will look into it.
