### ISSUE TITLE
Delimiters of new_taxdump

### ISSUE THREAD

**Issue by dnieuw** [DennisSchmitz/Jovian_archive#18]
Need to adjust the delimiters in the dmp files:

`for file in *.dmp; do awk '{gsub("\t",""); if(substr($0,length($0),length($0))=="|") print substr($0,0,length($0)-1); else print $0}' < ${file} > ${file}.delim; done`

**Comment by DennisSchmitz** [comment]
Yeah we used that line in our crontab, forgot to add it to the README. Once the wrapper is stable it should do it automatically. For now I`ll add it to the README explanation.

Linked to #7

**Comment by DennisSchmitz** [comment]
Updated README in ecb7236
