### ISSUE TITLE
Hardcoded nginx port, make it flexible

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#20]
In `bin/start_nginx.sh` the port `8083` is hardcoded. This should be made a variable that is imported from the pipeline_config.yaml. It is causing confusion when installing it outside our institute.

**Comment by florianzwagemaker** [comment]
Solved in https://github.com/DennisSchmitz/Jovian/commit/53645b6df60292487beac6e0e04da66873f0befe

Further development around and regarding to NGINX continues in #25
