### ISSUE TITLE
Some html output files are not generated.

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#26]
After running Jovian on  PE300 MiSeq data the following files are not generated (and hence the 404 error is showing up in the Notebook report).

- Sample_composition_graph.html -> log file not generated 
- Heatmap_index.html (and all the other heatmaps) -> log file not generated 
- IGVjs_index.html -> log file not generated

Is there a root cause for these three bugs? Is it all related to issue #12 ? In the rulegraph the rule Generate_index_html_file is topographically connected to the rules draw_heatmaps and quantify_output. Since there are no log files it is hard to get what went wrong.

snakemake_report.html (which directly relates to the missing files above, running it as standalone snakemake command outside the Snakefile generates a report based on the available data)

Building DAG of jobs...
Missing metadata for file results/heatmaps/Superkingdoms_heatmap.html
Missing metadata for file results/heatmaps/Virus_order_heatmap.html
Missing metadata for file results/heatmaps/Virus_family_heatmap.html
Missing metadata for file results/heatmaps/Virus_genus_heatmap.html
Missing metadata for file results/heatmaps/Virus_species_heatmap.html
Missing metadata for file results/heatmaps/Phage_order_heatmap.html
Missing metadata for file results/heatmaps/Phage_family_heatmap.html
Missing metadata for file results/heatmaps/Phage_genus_heatmap.html
Missing metadata for file results/heatmaps/Phage_species_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_phylum_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_class_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_order_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_family_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_genus_heatmap.html
Missing metadata for file results/heatmaps/Bacteria_species_heatmap.html
Missing metadata for file results/Taxonomic_rank_statistics.tsv
Missing metadata for file results/Virus_rank_statistics.tsv
Missing metadata for file results/Phage_rank_statistics.tsv
Missing metadata for file results/Bacteria_rank_statistics.tsv
Missing metadata for file results/profile_read_counts.csv
Missing metadata for file results/profile_percentages.csv
Missing metadata for file results/Sample_composition_graph.html
Missing metadata for file results/Heatmap_index.html
Missing metadata for file results/IGVjs_index.html
...

**Comment by thierryjanssens** [comment]
The log files for the upstream Concat_files and Merge_all_metrics_into_single_tsv rules are also empty. 

The broken workflow must have happened at the level of Merge_all_metrics_into_single_tsv. 
Is the merging step sensitive to possible missing data?

**Comment by DennisSchmitz** [comment]
I checked Thierry's run, has to do with issue #12 . The logfiles of the merge rule are supposed to be empty when there are no errors, so that's actually a good thing.

I`ll close this issue for now since it is a replicate of #12.
