### ISSUE TITLE
bcl2fastq onder jovian brengen

### ISSUE THREAD

**Issue by jeroencremer** [DennisSchmitz/Jovian_archive#28]
De demultiplexing zit momenteel nog bij de vings server.
Het zou mooi zijn wanneer dit ook op het grid kan, echter moet bcl2fastq geinstalleerd worden onder jovian.

Info
https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq_letterbooklet_15038058brpmi.pdf

**Comment by DennisSchmitz** [comment]
Sorry for the Dutch response, short English summary: we won't add demultiplexing functionality into Jovian.

Ha Jeroen, we gaan dat niet meer toevoegen aan Jovian. Jeroen Laros z'n groep gaat hier een oplossing voor bouwen in de nieuwe fase van het bioinformatica project, zodoende wordt onze implementatie dan redundant.

We kunnen hem wel in jouw home directory installeren zodat je het zelf kan gebruiken op het grid (zelfde setup als vings server)
