### ISSUE TITLE
Further development for Jovian wrapper [continued from #7]

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#30]
This is a continued issue for the general development of the Jovian wrapper as the original issue #7 is marked as closed.

Jovian wrapper issues will be marked as closed when specific milestones are set.

Requested features for upcoming versions of the Jovian wrapper:

- [x] Flexible and random symlinks as described in #25 
- [x] Configuring and starting of Jupyter processes
- [x] Starting of Nginx
- [x] Change in the installation of IGVjs (automatic by default)
- [x] flag `--clean` should also clear/remove the variables.yaml file
- [x] Jovian should 'remember'  installation steps so the user doesn't have to use the interactive installation with every working directory.
- [x] Setting up / downloading databases
- [x] Additional flag for making variables and sample sheet so Snakemake can be used standalone for debugging purposes

more features and/or requests will be added here later on

**Comment by DennisSchmitz** [comment]
@florianzwagemaker , I think the final point is implemented in the `dev` branch, right? Can it be closed?

**Comment by florianzwagemaker** [comment]
The last 2 points are being implemented in the dev branch but they're not finished yet. I will close this issue once these points are fully implemented and validated to be working as intended.

**Comment by florianzwagemaker** [comment]
https://github.com/DennisSchmitz/Jovian/commit/8d8e0c65252da5387ce7f29f3db00da75850e990 contains the functioning database installation script

**Comment by florianzwagemaker** [comment]
https://github.com/DennisSchmitz/Jovian/commit/70bfbf19504d9a5e38f6fab7230a8e94bf8124ee adds the `bash jovian -i <input_folder> --make-sample-sheet` flag for the jovian wrapper.

This will create the sample sheet and variables.yaml file but will not execute the snakefile.
Running this command + flag will make sure you can run the snakefile manually for debugging purposes.
