### ISSUE TITLE
r-base is (sometimes) a dependency for picard

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#32]
r-base needs to be added as a dependency to the scaffold_analysis.yaml conda template.

specifc version is r-base==3.5.1 (latest)

related to https://github.com/bioconda/bioconda-recipes/issues/3859

**Comment by florianzwagemaker** [comment]
Should be solved in https://github.com/DennisSchmitz/Jovian/commit/548068e4f77cad7d3fc91b32a1644bfaa5cbe37a

**Comment by thierryjanssens** [comment]
I have a similar experience that with certain samples Picard requires the ldpaths package:

ERROR	2019-05-10 11:27:12	ProcessExecutor	/data/BioGrid/ERVINGS/Runs_Respiratory_MiSEQ_RIVM/MiSeq_RUN_12APR2019/Jovian/.snakemake/conda/1bd8fc38/lib/R/bin/R: line 238: /data/BioGrid/ERVINGS/Runs_Respiratory_MiSEQ_RIVM/MiSeq_RUN_12APR2019/Jovian/.snakemake/conda/1bd8fc38/lib/R/etc/ldpaths: No such file or directory
[Fri May 10 11:27:12 CEST 2019] picard.analysis.CollectInsertSizeMetrics done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=536870912
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: R script picard/analysis/insertSizeHistogram.R failed with return code 1
	at picard.analysis.CollectInsertSizeMetrics.finish(CollectInsertSizeMetrics.java:184)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:164)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by thierryjanssens** [comment]
Perhaps ldpaths needs to be added to the scaffold_analysis.yaml conda template as well?

**Comment by thierryjanssens** [comment]
Forgot to re-open.

**Comment by thierryjanssens** [comment]
A similar case has been observed in the following issue:

https://github.com/conda-forge/r-base-feedstock/issues/67

**Comment by florianzwagemaker** [comment]
ldpaths is unfortunately not listed in conda as an independent package. Ldpaths as an issue is unfortunately out of our hands for that matter.
It however seems that deleting the particular conda environment and re-running the pipeline can help. The conda environment should be re-made when the pipeline starts.

will keep an eye out on the r-base issue you linked. Once published we can test it and if it indeed solves the issue then we should update the environment dependencies.

**Comment by DennisSchmitz** [comment]
Just thinking out loud here, haven't thoroughly read the linked r-base issue... But, would Singularity help with this?

**Comment by florianzwagemaker** [comment]
Closing for now,
Ldpaths itself is an issue related to
1. The conda-forge package
2. The filesystem latency

If you run into this issue then the best thing you can do is to simply rebuild the specific conda environment.
