### ISSUE TITLE
User-defined taxa for heatmaps

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#38]
As also suggested in issue #12, it would be nice if the user could provide taxa of interest to make heatmaps for. I suggest defaults will be provided, namely those we use now: viruses (without phages), phages (based on a number of families), and bacteria.

The actual list may go into the `profile/pipeline_parameters.yaml` file, which is passed to the script by Snakemake. (Probably to be used as Python dictionary: ranks as keys, and lists of taxa as values.)

This will make the script more flexible to support researchers interested in certain taxa (that are not currently in the heatmaps).

**Comment by samnooij** [comment]
I have been thinking a bit more about this and I think it's probably not worth the effort. If people really want to have other taxa in a figure, they can do that themselves using the data Jovian provides by writing their own script or by modifying `draw_heatmaps.py` and for example write something else where it says "Viruses" now. Viruses, phages, and bacteria seem like sane defaults that work in most settings.  
Building a user-friendly system around the script to facilitate a probably rare use-case does not seem like good use of time and resources. I think it would take a couple of days to get it right. And does anybody already want other taxa in heatmaps? (And also do that multiple times, justifying automation?)

I'm leaving the issue open for now as low-priority, nice-to-have. If somebody feels like devoting time to this it is still possible. I can try and help then if necessary.

**Comment by DennisSchmitz** [comment]
Agreed
