### ISSUE TITLE
Combine heatmaps in a single file per taxonomic group

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#39]
As also suggested in issue #12, it is probably easier and more logical if, for instance, all virus heatmaps are written to the same file, and different taxonomic ranks are accessible under different tabs. (For an example, see https://files.realpython.com/media/tabbed_layout.2566a4615fcf.gif, from https://realpython.com/python-data-visualization-bokeh/, in the section "Organizing Multiple Visualizations With Layouts".) Then only one file "Virus_heatmaps.html" would be generated, containing tabs for orders, families, genera and species.

If this is done, it might also be more convenient if the heatmaps are directly embedded in the final report notebook, instead of having links to the files. (What do you think @DennisSchmitz ?)

**Comment by DennisSchmitz** [comment]
That would indeed be much better!

**Comment by samnooij** [comment]
Issue tackled in https://github.com/DennisSchmitz/Jovian/commit/b090457b37d60102cef284e0829ed1dd8d249e3e. I will also adapt the Report Notebook to reflect these changes and visualise the heatmaps better.

**Comment by samnooij** [comment]
Heatmaps are embedded in the Report Notebook in 47101d9.
