### ISSUE TITLE
bash jovian

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#40]
Hi guys,

when trying to run the following command nothing is happening for hours:

bash jovian -i raw_data/

Now I realize I still have to run  the installer, but this is also hanging without apparently going anywhere.

bash jovian -ic

**Comment by thierryjanssens** [comment]
I do this in the Jovian folder (as a result of the git clone) and within the Jovian_master environment.

**Comment by DennisSchmitz** [comment]
I think I've found the problem, I'm guessing the `data/` folder doesn't exist yet? Can you test this for me please:

`mkdir data/`
`bash jovian -ic`

**Comment by thierryjanssens** [comment]
Unfortunately this does not solve the error. I am trying to get it working in two separate Jovian folders containg raw_data/ with fastq files from MiSeq runs.

One folder contained already the data/ folder, the other did not. 
Still it is hanging, at the installation stage (bash jovian -ic).


Several processes are active (see screenshot).

![image](https://user-images.githubusercontent.com/38220376/57510046-0c028300-7306-11e9-8dba-de3ee663619d.png)

**Comment by thierryjanssens** [comment]
Meanwhile it has been solved by not running this in an embedded terminal (e.g. jupyter notebook_.

**Comment by thierryjanssens** [comment]
A new error is popping up, when no /data folder is present:

jovian: line 469: data/variables.yaml: No such file or directory

When data/ is manually created with mkdir, the error is solved.

**Comment by thierryjanssens** [comment]
Additional errors are spit out in the log files. I am not sure if this puppeteer is essential for Jovian?
( /home/janssetk/.npm/_logs/2019-05-10T07_49_34_642Z-debug.log  )

16874 verbose npm  v6.7.0
16875 error code ELIFECYCLE
16876 error errno 1
16877 error puppeteer@0.13.0 install: `node install.js`
16877 error Exit status 1
16878 error Failed at the puppeteer@0.13.0 install script.
16878 error This is probably not a problem with npm. There is likely additional logging output above.
16879 verbose exit [ 1, true ]

**Comment by florianzwagemaker** [comment]
> A new error is popping up, when no /data folder is present:
> jovian: line 469: data/variables.yaml: No such file or directory
> When data/ is manually created with mkdir, the error is solved.

This is known for v0.9.2 (https://github.com/DennisSchmitz/Jovian/releases/tag/v0.9.2)
This error will be resolved soon with a patch (0.9.2.1)

> Additional errors are spit out in the log files. I am not sure if this puppeteer is essential for Jovian?
> ( /home/janssetk/.npm/_logs/2019-05-10T07_49_34_642Z-debug.log )
> 16874 verbose npm v6.7.0
> 16875 error code ELIFECYCLE
> 16876 error errno 1
> 16877 error puppeteer@0.13.0 install: node install.js
> 16877 error Exit status 1
> 16878 error Failed at the puppeteer@0.13.0 install script.
> 16878 error This is probably not a problem with npm. There is likely additional logging output above.
> 16879 verbose exit [ 1, true ]

This is a known error when installing IGVjs in our local (grid) system. As far as testing has shown, this error doesn't happen on other systems.
The error itself has no influence on the functions of the pipeline, notebooks or IGVjs and can be ignored

**Comment by DennisSchmitz** [comment]
> Meanwhile it has been solved by not running this in an embedded terminal (e.g. jupyter notebook_.

This is something to keep in mind for future versions. We're not testing for it because currently it's a niche case, however, in the future with more non-bioinformatician users this might pose a problem...

**Comment by florianzwagemaker** [comment]
Issue regarding data/variables.yaml is solved in https://github.com/DennisSchmitz/Jovian/commit/b5c52dc2423e06a0cebff47c1143294ca60395cf
