### ISSUE TITLE
Make Jovian compatible with gzipped fastq files

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#5]
Current version of Jovian only allows unzipped (=.fastq or .fq) files. Most often, input files are zipped via gunzip (extension= .gz) to reduce disk space. The pipeline should be compatible with these input files are not require files to be gunzipped first.

Requires updating of the sample_sheet script and Snakefile. Is probably as simple as including an `if statement [extension = .gz]; then zcat`.

**Comment by florianzwagemaker** [comment]
Not yet pushed to master branch.
but commit https://github.com/DennisSchmitz/Jovian/commit/0b347fcf80bb16b8102223155c1a0f476605f9e4 allows jovian to succesfully process zipped and unzipped fastq files without manual adjustments in the configuration or parameters.

This however only supports "paired" files.

Example:
```
R1.fastq
R2_fastq
--> works
```

```
R1.fastq.gz
R2.fastq.gz
--> works
```

```
R1.fastq
R2.fastq.gz
--> Doesn't work
```
