### ISSUE TITLE
Make background removal process more accessible to allow removal of other background organisms (e.g. rat, monkey, hamster genome for cell culture samples).

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#53]
We currently have HuGo background removal setup as default. However, this same method can be used to remove whichever genomic data. E.g. rat, hamster, monkey genome to remove background in cell culture experiments, or to remove the background based on the contents of the negative control.

Technically, Jovian is already capable of doing that (given that there are accurate references for those organisms). We should however make it more accessible by adding it to the wrapper and better explaining it in the wrapper.

**Comment by DennisSchmitz** [comment]
@samnooij , this would also require changing the annotation label in the `quantify_output` script: instead of `Human` I propose we call it something different. E.g. `Background`, `User specified filter`, etc. but I`m still not too sure about the name.

**Comment by DennisSchmitz** [comment]
@samnooij , only the annotation in the `quantify_output` script needs to be changed. After that, this issue can be closed.

**Comment by samnooij** [comment]
What would be the most appropriate term then? 'Host'? 'Genomic background'? Or just 'filtered reads' or something?
