### ISSUE TITLE
Optimization to typing-tool: Stop process if website is not accessible

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#54]
Currently the typing-tool implementation can take a long time to finish when the website is not accessible. It will wait for a time-out for each and every query even thought the website is not available.

This can be easily fixed by checked the exit status of a `cURL` and then stopping the process instead of waiting for all those time-outs.

**Comment by DennisSchmitz** [comment]
@robertverhagen can you help me with this? I mean, the code that does it easy (`cURL`). But I don't want to take the typingtools offline (since people depend on them) to simply test this little piece of code. Is that something you can assist in? Maybe make a temporary mirror to test it without taking the official website offline? (just brain storming here)

**Comment by florianzwagemaker** [comment]
This has been added in dev-branch commit: https://github.com/DennisSchmitz/Jovian/commit/c839bd5fb455cab56e52868d340c4a12af709021

The wrapper now checks whether a typingservice is online by looking at the HTTP status codes.
Anything other than statuscode 200 will cause the virustyping script to exit.
