### ISSUE TITLE
Add Jovian pre-flight check

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#6]
Add an extensionless bash file to check if Jovian has everything to run properly before running the full pipeline. For example, checking if all the necessary databases are present.

Also makes it possible to run Jovian with its own command instead of `snakemake --profile profile`
Similar to MetaMeta https://github.com/pirovc/metameta

**Comment by DennisSchmitz** [comment]
Continued in #7
