### ISSUE TITLE
Krona accession2taxid database doesn't exist in current version

### ISSUE THREAD

**Issue by florianzwagemaker** [DennisSchmitz/Jovian_archive#60]
Related to https://github.com/marbl/Krona/issues/113

The names of these files/databases have been changed, the names that are listed in the krona version that we use are no longer correct.
It's therefore not possible to download/update the krona databases (properly)
Should update from 2.7 to 2.7.1

**Comment by DennisSchmitz** [comment]
Since this Krona update entails only bug fixes I don't think we need extensive validation. Can you give it a quick test and implement it?

**Comment by florianzwagemaker** [comment]
Fixed in https://github.com/DennisSchmitz/Jovian/commit/4d0e1adc3c75f22fbf1e27500a301b92c860d0b7
