### ISSUE TITLE
Make a "Binder" of the Jovian report so people can see and browse a public example of the Jovian report straight from GitHub

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#69]
For the first public version of Jovian, and for the reviewers of the paper, we need to have a public example of the Jovian report. This is possible with a `binder`; a freely and publicly hosted Jupyter Notebook.

There are a couple of caveats however:
- We cannot make our own data public (human clinical data; privacy concerns)
- `binder` is a free service to enhance open science, in order to keep it free they kindly request you to not make big (>10MB) reports. Problem is, the Krona and heatmaps graphs are by themselves already bigger than 10MB. So we need to find a work-around for that: 1) stream them from an ftp 2) make a small/limited demo 3) link to already public examples.
- We need to make a separate public Jovian_binder repo, `binder` only works with public data. So this can only come online when we open up the Jovian and Jovian_binder repo's to the public.
- IGVjs won't work (I think), we should probably link to screenshots or to the examples of the IGVjs team's website.

**Comment by florianzwagemaker** [comment]
Done.

Binder Jovian report is available at: https://mybinder.org/v2/gh/DennisSchmitz/Jovian_binder/master?filepath=Notebook_report.ipynb

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/DennisSchmitz/Jovian_binder/master?filepath=Notebook_report.ipynb)
