### ISSUE TITLE
Make Jovian citable and create DOIs through Zenodo

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#71]
It would be nice to make Jovian easy to cite (and perhaps easier to find?) by linking the repository to [Zenodo](https://zenodo.org/) and automatically create a [DOI](https://zenodo.org/) for the release version (or each version?). Information on how to do this can be found on: https://guides.github.com/activities/citable-code/. You can also use a DOI badge on the README page, as shown in the bottom of this page.

(Of course, this works best when the project is public.)

**Comment by DennisSchmitz** [comment]
Will do once the repo is public.

**Comment by DennisSchmitz** [comment]
Jovian is public now and I've coupled Zenodo with the repo, it should activate on the next new release. I'll add the DOI badge to the frontpage afterwards.

**Comment by aschuerch** [comment]
Congrats Dennis and collaborators on making the repo public! Great work!

**Comment by DennisSchmitz** [comment]
Thanks Anita :)

**Comment by florianzwagemaker** [comment]
Zenodo has been added --> [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3666157.svg)](https://doi.org/10.5281/zenodo.3666157)

Currently only in dev branch but will be fully added in next release
