### ISSUE TITLE
Clarify `--unlock`: Explain that you need to specify the input folder otherwise it won't unlock.

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#75]
We need to clarify in the help message/README that you need to specify the input folder (i.e. `-i /location/to/input/folder/`) when doing the `--unlock` command. Otherwise it will not unlock. @RozemarijnVanDerPlaats was having some problems with this.

**Comment by florianzwagemaker** [comment]
It's probably a good idea to make a dedicated `--unlock` flag in the bash wrapper.  This will be both easier for the end user and more stable as a dedicated solution.

**Comment by florianzwagemaker** [comment]
Dedicated `--unlock` flag has been added to the wrapper in https://github.com/DennisSchmitz/Jovian/commit/3b71bd07d7b8fec376a460276e85d311aa86e469

Usage: `bash jovian -u` or `bash jovian --unlock`
