### ISSUE TITLE
profile_percentages.csv from rule quantify_output

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#76]
The read numbers as summarized in the rule quantify_output do not add up in all cases.
This results in negative percentages in the remaining section of the reads set.

**Comment by samnooij** [comment]
Can you check if it is the number of mapped reads that is (or seems) too high? This has been an unsolved issue for some time (see also #56 ). My guess is that it might be solved by tweaking the mapping method. It seems that most problems occur when there are many similar genomes/fragments in the sample (e.g. lots of one or few bacteria). Could that be the case in your sample?

(The 'remaining' is calculated by summing all the reads in different 'parts' (i.e. low quality, human reads, mapped to contigs) and subtracting that from the 'total reads' (i.e. the raw reads from the very start of the analysis). If those parts for some reason add up to a higher number than the total reads, the remaining part will become a negative number to add up to the total number.)

**Comment by samnooij** [comment]
duplicate of #56.
