### ISSUE TITLE
Superkingdom heatmap: leave fields with 0 contigs/reads blank

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#79]
As noted before in #41, I want superkingdom heatmaps to leave fields blank that have no contigs (and thus reads) assigned to them. This should make it easier to discern low abundance from absence.

---

"""
I have tried running the draw_heatmaps script in the directory you were working in (`/data/BioGrid/ERVINGS/Runs_Respiratory_MiSEQ_RIVM/MiSeq_RUN_06MAY2019/Jovian/`) and learned a few things:  
1. the heatmap function is not ready for empty data. I.e. if there are no taxa in the clade that it is going to plot, the script will fail. In this case, there were no viral species, so the pipeline got stuck there.
2. By filling in zeroes in otherwise empty (NaN) fields, the heatmap will fill in every single block with data and colour them in a very light shade, whereas before these fields were left empty/blank. I prefer the empty fields as that is the easiest way to tell the absence of certain taxa, I think.

So `draw_heatmaps` will require (at least) 2 fixes:
**1. Check if dataframe is empty, and if so, better write an empty file and report in the log file. --PRIORITY**
2. Disable plotting for fields with 0 contigs. (Change 0 values back to NaN before plotting, I guess.)

As for the `quantify_profiles`: I have not yet checked it. I hope it will be an easy fix with 'add a column of zeroes for each missing superkingdom'. I will report back later!
"""

_Originally posted by @samnooij in https://github.com/DennisSchmitz/Jovian/issues/41#issuecomment-491704153_

**Comment by samnooij** [comment]
I tried filling in 'missing values' in the dataframe before plotting, so that the heatmap always shows all samples and superkingdoms. I did this by putting zeroes where taxa were absent. This led to less intuitive, always grey heatmaps.

Now I tried changing the 0 values to NaN, which turned the whole heatmap black. Removing these NaN values brings us back to the initial version: absent taxa and samples for which no taxa appear to be present are left out of the heatmap.

So it looks like it is one or the other:  
- Either fill in all superkingdoms and samples, but create grey blocks of 0 reads  
- or leave empty values out of the heatmap, which causes some heatmaps to lack one or more superkingdoms, and also not all samples may show up

Both have their advantage and disadvantage, but I prefer the latter option that leaves out missing data from the visualisation. @DennisSchmitz what do you think?

**Comment by samnooij** [comment]
If you agree, the issue should be fixed with https://github.com/DennisSchmitz/Jovian/commit/3485cae858c2d6aecca9876e49969fe358444fea

**Comment by DennisSchmitz** [comment]
Yeah that's too bad then, fine by me! You wanna close this issue or leave it open until it's committed to the master branch?
