### ISSUE TITLE
Read counts in Sample_composition_graph.html may still not be counted/added correctly

### ISSUE THREAD

**Issue by samnooij** [DennisSchmitz/Jovian_archive#8]
This is an issue that I have tried to solve before, but it seems that the bug has not yet completely been fixed.

As it turns out, the `Sample_composition_graph.html` may show percentages > 100%. I found previously that this may be due to the sorting of samples (when the order becomes mixed, the numbers of one sample may be mixed with another, e.g. the number of bacteria in sample 1 are switched with the number of bacteria in sample 3). I tried to solve this by sorting the list of samples beforehand, but with more complex sample names _(letter and number combinations: sort alphabetically or numerically?)_ the sorting may not always go right automatically.

Therefore, I propose to **look into the sorting of samples with more complex names**. Check if the problem is indeed there and fix it. Also **include some checks to make sure the order is right** (assert lines?).

If the problem is somewhere else, more bug-hunting is necessary.

**Comment by DennisSchmitz** [comment]
Any update on this @samnooij ?

**Comment by samnooij** [comment]
I was waiting if other people had problems with other data, but I have not seen any more problems with incorrect read counts. It seems the issue has been solved.

**Comment by DennisSchmitz** [comment]
Nice, then I`m closing it for now!
