### ISSUE TITLE
High coverage samples 

### ISSUE THREAD

**Issue by jeroencremer** [DennisSchmitz/Jovian_archive#83]
When the coverage is high >1000, sometimes the sequence are in different contigs.

**Comment by DennisSchmitz** [comment]
@jeroencremer , what do you mean exactly? You mean a full genome is split over multiple contigs when coverage is high? Or do you mean when you are using the `bash jovian --mode relaxed` mode? Because that is caused by introducing extra noise due to lower stringency thresholds.

**Comment by DennisSchmitz** [comment]
Discussed it with Jeroen, it's about how high coverage samples sometimes get split into multiple contigs. I've explained that this is a known issue with de novo assembly in general and that this is currently out of scope for Jovian.

The quick and dirty solution is to downsample your data via `seqtk sample` (https://github.com/lh3/seqtk). A more elegant solution is to artificially normalize your coverage via `bbtools`/`bbnorm` (http://seqanswers.com/forums/showthread.php?t=49763). 

In the future we'll look into incorporating the second solution, but this requires additional validation. For now, I`m closing this issue.
