### ISSUE TITLE
Last step of Jovian fails (/tmp/etc/nginx/)

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#86]
In the last step of Jovian it crashes, as it cannot write to /tmp/etc/nginx/ .
This error has just occurred today (in my case).

The output was as follows:
Cleaning up...
	Removing empty folders...
	Removing temporary files...
	Creating symlinks for the interactive genome viewer...
find: ‘/tmp/etc/nginx/default-site/*’: No such file or directory
mkdir: cannot create directory ‘/tmp/etc/nginx’: Permission denied
ln: failed to create symbolic link ‘/tmp/etc/nginx/default-site/iMsc2QboA2GWlaJ9icMWYPRJsR445xoo’: No such file or directory
CalledProcessError in line 845 of /data/BioGrid/ERVINGS/Runs_Respiratory_MiSEQ_RIVM/MiSeq_RUN_OneTest_09AUG2019/Jovian/Snakefile:
Command 'set -euo pipefail;  echo -e "
Cleaning up..."
        echo -e "	Removing empty folders..."
        find data -depth -type d -not \( -path data/scaffolds_raw -prune \) -empty -delete

        echo -e "	Removing temporary files..."
        if [ "1" != "0" ]
        then
            rm -rf data/FastQC_pretrim/
            rm -rf data/FastQC_posttrim/
            rm -rf data/cleaned_fastq/fastq_without_HuGo_removal/
            rm -f data/scaffolds_filtered/*_insert_size_histogram.pdf
            rm -f data/scaffolds_filtered/*_insert_size_metrics.txt
            rm -f data/scaffolds_filtered/*_MinLenFiltSummary.stats
            rm -f data/scaffolds_filtered/*_perMinLenFiltScaffold.stats
            rm -f data/scaffolds_filtered/*nt.fasta.sizes
            rm -f data/scaffolds_filtered/*.windows
            rm -f data/taxonomic_classification/*.taxtab
            rm -f data/taxonomic_classification/*.taxMagtab
        else
            echo -e "		You chose to not remove temp files: the human genome alignment files are not removed."
        fi

        echo -e "	Creating symlinks for the interactive genome viewer..."
        bin/set_symlink.sh

        echo -e "	Generating HTML index of log files..."
        tree -hD --dirsfirst -H "../logs" -L 2 -T "Logs overview" --noreport --charset utf-8 -P "*" -o results/logfiles_index.html logs/

        echo -e "	Generating Snakemake report..."
        snakemake --unlock --config sample_sheet=sample_sheet.yaml
        snakemake --report results/snakemake_report.html --config sample_sheet=sample_sheet.yaml

        echo -e "Finished"' returned non-zero exit status 1.
  File "/data/BioGrid/ERVINGS/Runs_Respiratory_MiSEQ_RIVM/MiSeq_RUN_OneTest_09AUG2019/Jovian/Snakefile", line 845, in __onsuccess

**Comment by DennisSchmitz** [comment]
I've just tried doing the same analysis (in your folder under my username). I didn't get an error. I also separately tried some of the commands that were causing the problems, they also worked as intended. Maybe the `/tmp/` was temporarily unavailable? Of maybe your user rights are somehow messed up and you cannot write in `/tmp/`?

**Comment by DennisSchmitz** [comment]
Found it, the folder is non-writable since another user already created it before you. In this case it was @florianzwagemaker , we should add a `chmod` to the script to open it up to everyone.

For now, Flo, can you make this folder writable for everyone?

**Comment by florianzwagemaker** [comment]
I'm assuming this problem is more related to our `/tmp/` folder than the scripts we use.
Our scripts already include a `chmod` to make `/tmp/etc/nginx` writable
`find /tmp/etc/nginx/ -user ${currentuser} -exec chmod 777 {} \;` in https://github.com/DennisSchmitz/Jovian/commit/337976c6ccbd066cf1d466f3d4866d72ed6e636e

Since the entire `/tmp/etc/nginx/*` folder didn't exist on the server where this happened, I would guess that this was caused by an (automatic?) cleanup of the `/tmp` directory...

Has nginx been restarted on this particular server?

**Comment by DennisSchmitz** [comment]
The problem was that there was an old version of the pipeline running in the background. Back when it was intended for a single-user environment. Current versions of the pipeline should not have this bug/error. Closing it.
